"""One-off generator for the Phase 2 statement-parsing test fixtures.

Run manually (`uv run --extra fixture-gen python scripts/generate_statement_fixtures.py`)
whenever fixtures need regenerating. Output is committed as static files —
never regenerated by tests or CI. All data below is synthetic; nothing here
represents a real bank, person, or transaction.
"""

import csv
import io
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "statements"


@dataclass
class Txn:
    year: int
    month: int
    day: int
    description: str
    amount: Decimal  # signed: negative = debit/outflow, positive = credit/inflow


TRANSACTIONS = [
    Txn(2024, 1, 3, "Grocery Mart #4471", Decimal("-54.23")),
    Txn(2024, 1, 5, "Salary Deposit Acme Corp", Decimal("2500.00")),
    Txn(2024, 1, 7, "Netflix Subscription", Decimal("-15.99")),
    Txn(2024, 1, 10, "Coffee Shop Downtown", Decimal("-6.75")),
    Txn(2024, 1, 12, "Electric Utility Co", Decimal("-112.40")),
    Txn(2024, 1, 15, "Transfer From Savings", Decimal("300.00")),
    Txn(2024, 1, 18, "Gas Station 66", Decimal("-48.10")),
    Txn(2024, 1, 22, "Refund Online Store", Decimal("23.50")),
    Txn(2024, 1, 25, "Gym Membership Fee", Decimal("-40.00")),
    Txn(2024, 1, 28, "Atm Withdrawal", Decimal("-100.00")),
]

OPENING_BALANCE = Decimal("5000.00")


def running_balances() -> list[Decimal]:
    balances = []
    balance = OPENING_BALANCE
    for txn in TRANSACTIONS:
        balance += txn.amount
        balances.append(balance)
    return balances


def write_csv_rows(path: Path, header: list[str], rows: list[list[str]]) -> None:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(header)
    writer.writerows(rows)
    path.write_text(buf.getvalue(), encoding="utf-8")


def gen_csv_clean_standard(path: Path) -> None:
    rows = [
        [f"{t.month:02d}/{t.day:02d}/{t.year}", t.description, f"{t.amount:.2f}"]
        for t in TRANSACTIONS
    ]
    write_csv_rows(path, ["Date", "Description", "Amount"], rows)


def gen_csv_debit_credit_columns(path: Path) -> None:
    rows = []
    for t in TRANSACTIONS:
        debit = f"{-t.amount:.2f}" if t.amount < 0 else ""
        credit = f"{t.amount:.2f}" if t.amount > 0 else ""
        rows.append([f"{t.day:02d}-{t.month:02d}-{t.year}", t.description, debit, credit])
    write_csv_rows(path, ["Value Date", "Narration", "Withdrawal Amt", "Deposit Amt"], rows)


def gen_csv_reordered_positive_debit(path: Path) -> None:
    rows = []
    for t in TRANSACTIONS:
        sign_type = "DR" if t.amount < 0 else "CR"
        date_str = f"{t.month:02d}/{t.day:02d}/{t.year}"
        rows.append([t.description, sign_type, f"{abs(t.amount):.2f}", date_str])
    write_csv_rows(path, ["Particulars", "Type", "Amt", "Txn Date"], rows)


def gen_csv_single_column_balance_inference(path: Path) -> None:
    rows = []
    for t, bal in zip(TRANSACTIONS, running_balances(), strict=True):
        date_str = f"{t.year}-{t.month:02d}-{t.day:02d}"
        rows.append([date_str, t.description, f"{abs(t.amount):.2f}", f"{bal:.2f}"])
    write_csv_rows(path, ["Date", "Details", "Amount", "Balance"], rows)


def gen_csv_with_banner_rows(path: Path) -> None:
    buf = io.StringIO()
    buf.write("Fintell Demo Bank\n")
    buf.write("Statement Period: Jan 01 2024 - Jan 31 2024\n")
    buf.write("\n")
    writer = csv.writer(buf)
    writer.writerow(["Date", "Description", "Amount"])
    for t in TRANSACTIONS:
        writer.writerow([f"{t.month:02d}/{t.day:02d}/{t.year}", t.description, f"{t.amount:.2f}"])
    path.write_text(buf.getvalue(), encoding="utf-8")


def gen_csv_malformed_rows(path: Path) -> None:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Date", "Description", "Amount"])
    for i, t in enumerate(TRANSACTIONS):
        if i == 3:
            writer.writerow(["not-a-date", t.description, f"{t.amount:.2f}"])
            continue
        if i == 6:
            writer.writerow([f"{t.month:02d}/{t.day:02d}/{t.year}", t.description, ""])
            continue
        writer.writerow([f"{t.month:02d}/{t.day:02d}/{t.year}", t.description, f"{t.amount:.2f}"])
    path.write_text(buf.getvalue(), encoding="utf-8")


MONTH_NAMES = [
    "",
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]


def gen_pdf_table_extractable(path: Path) -> None:
    data = [["Date", "Description", "Amount", "Balance"]]
    for t, bal in zip(TRANSACTIONS, running_balances(), strict=True):
        date_str = f"{t.day:02d} {MONTH_NAMES[t.month]} {t.year}"
        data.append([date_str, t.description, f"{t.amount:.2f}", f"{bal:.2f}"])

    c = canvas.Canvas(str(path), pagesize=letter)
    table = Table(data, colWidths=[1.3 * inch, 2.6 * inch, 1.0 * inch, 1.0 * inch])
    table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ]
        )
    )
    table.wrapOn(c, 500, 700)
    table.drawOn(c, 40, 400)
    c.save()


def gen_pdf_text_no_table(path: Path) -> None:
    c = canvas.Canvas(str(path), pagesize=letter)
    c.setFont("Helvetica", 10)
    y = 750
    c.drawString(40, y, "Fintell Demo Bank — Statement")
    y -= 30
    for t in TRANSACTIONS:
        line = f"{t.day:02d}/{t.month:02d}/{t.year}   {t.description}   {t.amount:.2f}"
        c.drawString(40, y, line)
        y -= 18
    c.save()


def gen_pdf_scanned_needs_ocr(path: Path) -> None:
    width, height = 1700, 2200  # ~200 DPI letter-size
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    try:
        font = ImageFont.truetype("arial.ttf", 28)
    except OSError:
        font = ImageFont.load_default()

    y = 100
    draw.text((80, y), "Fintell Demo Bank -- Statement (Scanned Copy)", fill="black", font=font)
    y += 70
    for t in TRANSACTIONS:
        line = f"{t.day:02d}/{t.month:02d}/{t.year}   {t.description}   {t.amount:.2f}"
        draw.text((80, y), line, fill="black", font=font)
        y += 50

    c = canvas.Canvas(str(path), pagesize=letter)
    page_width, page_height = letter
    c.drawInlineImage(image, 0, 0, width=page_width, height=page_height)
    c.save()


def main() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    gen_csv_clean_standard(FIXTURES_DIR / "csv_clean_standard.csv")
    gen_csv_debit_credit_columns(FIXTURES_DIR / "csv_debit_credit_columns.csv")
    gen_csv_reordered_positive_debit(FIXTURES_DIR / "csv_reordered_columns_positive_debit.csv")
    gen_csv_single_column_balance_inference(
        FIXTURES_DIR / "csv_single_column_balance_inference.csv"
    )
    gen_csv_with_banner_rows(FIXTURES_DIR / "csv_with_banner_rows.csv")
    gen_csv_malformed_rows(FIXTURES_DIR / "csv_malformed_rows.csv")
    gen_pdf_table_extractable(FIXTURES_DIR / "pdf_table_extractable.pdf")
    gen_pdf_text_no_table(FIXTURES_DIR / "pdf_text_no_table.pdf")
    gen_pdf_scanned_needs_ocr(FIXTURES_DIR / "pdf_scanned_needs_ocr.pdf")
    print(f"Wrote fixtures to {FIXTURES_DIR}")


if __name__ == "__main__":
    main()
