"""add statement parsing tables

Revision ID: 15bd86c1e4ea
Revises: 7ca738897a8d
Create Date: 2026-08-26 22:06:19.765322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bd86c1e4ea'
down_revision: Union[str, Sequence[str], None] = '7ca738897a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_type', sa.String(length=32), nullable=False),
    sa.Column('header_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('header_fingerprint_normalized', sa.Text(), nullable=False),
    sa.Column('column_map_json', sa.JSON(), nullable=False),
    sa.Column('date_format', sa.String(length=64), nullable=False),
    sa.Column('amount_sign_convention', sa.String(length=64), nullable=False),
    sa.Column('regex_pattern', sa.Text(), nullable=True),
    sa.Column('sample_lines_json', sa.JSON(), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('times_rejected', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_profiles_header_fingerprint_hash'), 'bank_profiles', ['header_fingerprint_hash'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_hint', sa.String(length=255), nullable=True),
    sa.Column('bank_profile_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('detected_structure', sa.String(length=32), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parse_method', sa.String(length=32), nullable=True),
    sa.Column('bank_profile_match_score', sa.Float(), nullable=True),
    sa.Column('row_count_total', sa.Integer(), nullable=False),
    sa.Column('row_count_parsed', sa.Integer(), nullable=False),
    sa.Column('row_count_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_profile_id'], ['bank_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('parse_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('raw_line_text', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_failures_statement_id'), 'parse_failures', ['statement_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_merchant', sa.Text(), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('categorization_method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_line_text', sa.Text(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_parse_failures_statement_id'), table_name='parse_failures')
    op.drop_table('parse_failures')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_bank_profiles_header_fingerprint_hash'), table_name='bank_profiles')
    op.drop_table('bank_profiles')
    # ### end Alembic commands ###
