"""add accounts and transaction_splits tables

Revision ID: 27e97f6a3b7f
Revises: 2fcfb6b34c40
Create Date: 2026-08-26 22:59:39.517343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e97f6a3b7f'
down_revision: Union[str, Sequence[str], None] = '2fcfb6b34c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('transaction_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_splits_transaction_id'), 'transaction_splits', ['transaction_id'], unique=False)
    op.add_column('statements', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_statements_account_id'), 'statements', ['account_id'], unique=False)
    op.create_foreign_key(None, 'statements', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_column('transactions', 'account_id')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_index(op.f('ix_statements_account_id'), table_name='statements')
    op.drop_column('statements', 'account_id')
    op.drop_index(op.f('ix_transaction_splits_transaction_id'), table_name='transaction_splits')
    op.drop_table('transaction_splits')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
