"""add llm_decision_log and llm_batch_calls tables

Revision ID: 2fcfb6b34c40
Revises: d1796c1bbe9a
Create Date: 2026-08-26 22:36:57.380445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcfb6b34c40'
down_revision: Union[str, Sequence[str], None] = 'd1796c1bbe9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_batch_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=False),
    sa.Column('merchant_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_decision_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_merchant', sa.Text(), nullable=False),
    sa.Column('cleaned_merchant', sa.String(length=255), nullable=False),
    sa.Column('llm_category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['llm_batch_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_decision_log_cleaned_merchant'), 'llm_decision_log', ['cleaned_merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_decision_log_cleaned_merchant'), table_name='llm_decision_log')
    op.drop_table('llm_decision_log')
    op.drop_table('llm_batch_calls')
    # ### end Alembic commands ###
