"""add merchant_lookup table

Revision ID: d1796c1bbe9a
Revises: 15bd86c1e4ea
Create Date: 2026-08-26 22:20:49.044867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1796c1bbe9a'
down_revision: Union[str, Sequence[str], None] = '15bd86c1e4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_lookup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_pattern', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_from_llm', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_lookup_raw_pattern'), 'merchant_lookup', ['raw_pattern'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_lookup_raw_pattern'), table_name='merchant_lookup')
    op.drop_table('merchant_lookup')
    # ### end Alembic commands ###
