"""Starter merchant_lookup entries.

These are public brand names used purely as categorization reference data
(the same kind of thing every fintech categorization engine ships with) —
not real transaction or personal financial data, which never appears
anywhere in this repo.
"""

SEED_MERCHANTS: list[tuple[str, str]] = [
    # (display name, category)
    ("Walmart", "groceries"),
    ("Whole Foods Market", "groceries"),
    ("Trader Joes", "groceries"),
    ("Kroger", "groceries"),
    ("Safeway", "groceries"),
    ("Costco Wholesale", "groceries"),
    ("Aldi", "groceries"),
    ("McDonalds", "dining"),
    ("Chipotle Mexican Grill", "dining"),
    ("Starbucks", "dining"),
    ("Chick Fil A", "dining"),
    ("Olive Garden", "dining"),
    ("Subway", "dining"),
    ("Dominos Pizza", "dining"),
    ("Dunkin", "dining"),
    ("Swiggy", "food_delivery"),
    ("Zomato", "food_delivery"),
    ("DoorDash", "food_delivery"),
    ("Uber Eats", "food_delivery"),
    ("Grubhub", "food_delivery"),
    ("Postmates", "food_delivery"),
    ("Uber", "transit"),
    ("Lyft", "transit"),
    ("Metro Transit", "transit"),
    ("Bart", "transit"),
    ("Pge", "utilities"),
    ("Con Edison", "utilities"),
    ("Comcast", "utilities"),
    ("At&t", "utilities"),
    ("Verizon", "utilities"),
    ("Netflix", "subscriptions"),
    ("Spotify", "subscriptions"),
    ("Disney Plus", "subscriptions"),
    ("Amazon Prime", "subscriptions"),
    ("Hulu", "subscriptions"),
    ("Youtube Premium", "subscriptions"),
    ("Apple Music", "subscriptions"),
    ("Icloud Storage", "subscriptions"),
    ("Amc Theatres", "entertainment"),
    ("Regal Cinemas", "entertainment"),
    ("Steam", "entertainment"),
    ("Playstation Network", "entertainment"),
    ("Xbox Live", "entertainment"),
    ("Amazon", "shopping"),
    ("Target", "shopping"),
    ("Best Buy", "shopping"),
    ("Ikea", "shopping"),
    ("Home Depot", "shopping"),
    ("Delta Air Lines", "travel"),
    ("United Airlines", "travel"),
    ("Marriott", "travel"),
    ("Airbnb", "travel"),
    ("Expedia", "travel"),
    ("Cvs Pharmacy", "health"),
    ("Walgreens", "health"),
    ("Planet Fitness", "health"),
    ("Anytime Fitness", "health"),
    ("Overdraft Fee", "fees"),
    ("Atm Fee", "fees"),
    ("Monthly Service Fee", "fees"),
    ("Wire Transfer Fee", "fees"),
]
